### ISSUE TITLE
how do i load multiple api keys of same service?

### ISSUE THREAD

**Issue by sahadev0079** [owasp-amass/amass#956]
This format works? 

```
- name: FullHunt
    creds:
      account: 
        apikey: null
     account2:
       apikey: null
  - name: GitHub
    ttl: 4320
    creds:
      accountname: 
        apikey: null
     accountname2:
        apikey: null
```
