### ISSUE TITLE
configuration api keys is not working 

### ISSUE THREAD

**Issue by kiro6** [owasp-amass/amass#978]
using this conf file : 

-  conf.yaml 
```yaml
options:
  datasources: "./datasources.yaml" # the file path that will point to the data source configuration
```

-  datasources.yaml 
```yaml 
  - name: Censys
    ttl: 10080
    creds:
      account: 
        apikey: key
        secret: secret

  - name: VirusTotal
    ttl: 10080
    creds:
      account: 
        apikey: key
```

-  print data sources 
```bash 
amass enum -list -config ./conf.yaml

Censys                      cert                        

VirusTotal                  api                         

```
VirusTotal and Censys still empty i read the doc and i think i followed it correctly
